import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import styled from 'styled-components';

import { CvPrintablePage } from '@/components/cv';

import styles from '../styles/Home.module.css';


const Cv: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title>My CV</Title>
        <Link href="/">Home</Link>
        <CvPrintablePage />
      </main>
    </>
  );
};

const Title = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: greenyellow;
`;

export default Cv;
