import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import styled from 'styled-components';

import { Editor } from '@/components/cv';

const Cv: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Header>
          <Title>My CV</Title>
          <Link href="/">Home</Link>
        </Header>
        <Editor />
      </Container>
    </>
  );
};

const Container = styled.div`
  height: 100%;
  display: grid;
  grid-template-rows: 70px 1fr;
`;

const Header = styled.header`
  background-color: hsl(210 10% 5%);
  display: flex;
  align-items: center;
  padding: 0 20px;
  gap: 20px;
`;

const Title = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: greenyellow;
`;

export default Cv;
