import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import styled from 'styled-components';
import { unstable_getServerSession } from 'next-auth';

import { Editor } from '@/components/editor';
import { AuthButtonContainer } from '@/components/common';
import { wrapper } from '@/state/store';
import { sessionSlice } from '@/state/session';

import { authOptions } from './api/auth/[...nextauth]';

const { actions } = sessionSlice;

export const getServerSideProps = wrapper.getServerSideProps(store => async ({ req, res }) => {
  const session = await unstable_getServerSession(req, res, authOptions);
  store.dispatch(actions.setSession(session));

  // I am returning the session here, but I don't think I need to but I get an typescript error if I don't
  return {
    props: {}
  };
});

const EditorPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header>
          <Title>My CV</Title>
          <Link href="/">Home</Link>
          <AuthButtonContainer />
        </Header>
        <Editor />
      </Container>
    </>
  );
};

export default EditorPage;

const Container = styled.div`
  height: 100%;
  display: grid;
  grid-template-rows: 70px 1fr;
`;

const Header = styled.header`
  background-color: hsl(210 10% 5%);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 20px;
  gap: 20px;
`;

const Title = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: greenyellow;
`;
