import type { NextPage } from 'next';
import Head from 'next/head';
import { connect } from 'react-redux';
import { unstable_getServerSession } from 'next-auth';

import { Landing } from '@/components/landing';
import { wrapper, AppState } from '@/state/store';
import { sessionSlice } from '@/state/session';

import { authOptions } from './api/auth/[...nextauth]';

const { actions } = sessionSlice;

export const getServerSideProps = wrapper.getServerSideProps(store => async ({ req, res }) => {
  const session = await unstable_getServerSession(req, res, authOptions);
  store.dispatch(actions.setSession(session));

  console.log('*** session -> ', session);

  // I am returning the session here, but I don't think I need to but I get an typescript error if I don't
  return {
    props: {}
  };
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
    </>
  );
};



export default connect((state: AppState) => state)(Home);
