import type { NextPage } from 'next';
import Head from 'next/head';
import { unstable_getServerSession } from 'next-auth';

import { Home } from '@/components/home';
import { wrapper } from '@/state/store';
import { sessionSlice } from '@/state/session';

import { authOptions } from './api/auth/[...nextauth]';

const { actions } = sessionSlice;

export const getServerSideProps = wrapper.getServerSideProps(store => async ({ req, res }) => {
  const session = await unstable_getServerSession(req, res, authOptions);
  store.dispatch(actions.setSession(session));

  // I am returning the session here, but I don't think I need to but I get an typescript error if I don't
  return {
    props: {}
  };
});

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
};

export default Home;
